name: Release Project

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
      - name: Build Project
        run: poetry build

      - name: Release to GitHub
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*.whl
            dist/*.tar.gz
